<script setup>
import { computed, h, ref, watch } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import { Eye, Plus } from '@lucide/vue';
import AppLayout from '@/layouts/AppLayout.vue';
import Card from '@/components/ui/Card.vue';
import Button from '@/components/ui/Button.vue';
import Badge from '@/components/ui/Badge.vue';
import Input from '@/components/ui/Input.vue';
import DataTable from '@/components/ui/DataTable.vue';
import Modal from '@/components/ui/Modal.vue';
import Tooltip from '@/components/ui/Tooltip.vue';
import { useToast } from '@/composables/useToast';
import { navGroups } from '@/lib/nav-items.js';
import { formatMoney, sumMoney } from '@/lib/money';
import { formatBsDate } from '@/lib/format';
import Create from './Create.vue';

const props = defineProps({
    journalVouchers: {
        type: Array,
        default: () => [],
    },
    accounts: {
        type: Array,
        default: () => [],
    },
    correctionFiscalYear: {
        type: Object,
        default: null,
    },
});

const page = usePage();
const { toast } = useToast();

const isAdmin = computed(() => page.props.auth?.user?.role?.slug === 'admin');
const navItems = computed(() => navGroups(isAdmin.value));

// Flash status is watched (not just read on mount) because posting a voucher
// redirects back to this same route + component, which Inertia re-renders
// in place without an onMounted re-run.
watch(
    () => page.props.flash?.status,
    (status) => {
        if (status) toast({ message: status, variant: 'success' });
    },
    { immediate: true },
);

// There is no GET /journal-vouchers/create route on the backend (only index +
// store exist, and route files are off-limits for this task), so the create
// form is not a separate page. Instead it's toggled in-place on this same
// /journal-vouchers route: clicking "New journal voucher" swaps the list view
// for the <Create> component, and posting redirects back to this same index
// route, which Inertia re-renders with fresh props before we flip back to the
// list.
const showCreateForm = ref(false);

const voucherTypeLabels = {
    opening_balance: 'Opening Balance',
    journal: 'Journal',
    closing_entry: 'Closing Entry',
    roll_forward_adjustment: 'Roll Forward Adjustment',
    reversal: 'Reversal',
};

// Ledger-side labels only. These are NOT the printed document numbers: a
// sale's printed invoice number comes from its own stored invoice_number
// (CONTRACTS C7), and this screen is the raw voucher ledger.
const voucherTypePrefixes = {
    opening_balance: 'OB',
    journal: 'JV',
    closing_entry: 'CL',
    roll_forward_adjustment: 'RFA',
    reversal: 'REV',
};

// The voucher model is serialised whole, so `date` arrives as a full ISO
// timestamp; the calendar day is all this screen shows.
function adDate(value) {
    return typeof value === 'string' ? value.slice(0, 10) : '';
}

function voucherTypeLabel(type) {
    return voucherTypeLabels[type] ?? type;
}

function voucherLabel(voucher) {
    const prefix = voucherTypePrefixes[voucher.voucher_type] ?? 'JV';
    return `${prefix}-${voucher.voucher_number}`;
}

// Exact string arithmetic, never Number(): the lines arrive as 2dp decimal
// strings and a float sum down a long voucher drifts a paisa.
function voucherAmount(voucher) {
    return sumMoney(voucher.lines.map((line) => line.debit ?? '0.00'));
}

const selectedVoucher = ref(null);

function viewVoucher(voucher) {
    selectedVoucher.value = voucher;
}

function onDetailOpenChange(value) {
    if (!value) selectedVoucher.value = null;
}

const statusVariants = {
    posted: 'success',
    cancelled: 'danger',
};

const statusLabels = {
    posted: 'Posted',
    cancelled: 'Cancelled',
};

// Cancel is only offered for a manually-posted 'journal' voucher - every
// other voucher_type is generated by another module's own record (Sale,
// Purchase, Payment, ...) or by FiscalYear's own bookkeeping (opening
// balance/closing entry/roll-forward) and must be cancelled from there
// instead. This mirrors the guard in JournalVoucher::cancel() itself
// (the backend still rejects it either way; this just avoids offering a
// button that would only fail).
const cancelling = ref(null);
const cancelForm = useForm({ reason: '' });

function openCancel(voucher) {
    cancelling.value = voucher;
    cancelForm.reset();
    cancelForm.clearErrors();
}

function onCancelOpenChange(value) {
    if (!value) cancelling.value = null;
}

function submitCancel() {
    cancelForm.post(`/journal-vouchers/${cancelling.value.id}/cancel`, {
        preserveScroll: true,
        onSuccess: () => {
            cancelling.value = null;
        },
    });
}

const columns = [
    {
        id: 'dateBs',
        header: 'Date (BS)',
        numeric: false,
        cell: ({ row }) => formatBsDate(row.original.date) || '—',
    },
    {
        id: 'dateAd',
        header: 'Date (AD)',
        numeric: false,
        cell: ({ row }) => adDate(row.original.date),
    },
    {
        id: 'type',
        header: 'Type',
        numeric: false,
        cell: ({ row }) => voucherTypeLabel(row.original.voucher_type),
    },
    {
        id: 'voucher_number',
        header: 'Voucher #',
        numeric: false,
        cell: ({ row }) => voucherLabel(row.original),
    },
    { accessorKey: 'narration', header: 'Narration' },
    {
        id: 'fiscal_year',
        header: 'Fiscal Year',
        numeric: false,
        cell: ({ row }) => row.original.fiscal_year?.name ?? '—',
    },
    {
        id: 'amount',
        header: 'Amount',
        numeric: true,
        cell: ({ row }) => formatMoney(voucherAmount(row.original)),
    },
    {
        id: 'created_by',
        header: 'Created By',
        numeric: false,
        cell: ({ row }) => row.original.creator?.name ?? '—',
    },
    {
        id: 'status',
        header: 'Status',
        numeric: false,
        cell: ({ row }) =>
            h(Badge, { variant: statusVariants[row.original.status] ?? 'neutral' }, () => statusLabels[row.original.status] ?? row.original.status),
    },
    {
        id: 'actions',
        header: 'Actions',
        numeric: false,
        cell: ({ row }) =>
            h('div', { class: 'flex items-center gap-2' }, [
                h(Tooltip, { label: 'View lines' }, () =>
                    h(
                        'button',
                        {
                            type: 'button',
                            class: 'flex h-[26px] w-[26px] items-center justify-center bg-primary-tint text-primary transition-[filter] duration-150 ease-out hover:brightness-95',
                            'aria-label': 'View lines',
                            onClick: () => viewVoucher(row.original),
                        },
                        [h(Eye, { class: 'h-[13px] w-[13px]' })],
                    ),
                ),
                isAdmin.value && row.original.status === 'posted' && row.original.voucher_type === 'journal'
                    ? h(
                          Button,
                          {
                              variant: 'secondary',
                              tone: 'purple',
                              type: 'button',
                              onClick: () => openCancel(row.original),
                          },
                          () => 'Cancel',
                      )
                    : null,
            ]),
    },
];
</script>

<template>
    <AppLayout title="Journal Vouchers" :nav-items="navItems">
        <template v-if="showCreateForm">
            <Create
                :accounts="accounts"
                :correction-fiscal-year="correctionFiscalYear"
                @cancel="showCreateForm = false"
                @posted="showCreateForm = false"
            />
        </template>

        <template v-else>
            <div class="mb-4 flex items-center justify-between">
                <h2 class="text-base font-bold text-text-strong">Journal Vouchers</h2>
                <Button v-if="isAdmin" variant="primary" tone="purple" @click="showCreateForm = true">
                    <Plus class="size-4" />
                    New journal voucher
                </Button>
            </div>

            <Card variant="panel">
                <DataTable :columns="columns" :data="journalVouchers" :page-size="10" empty-message="No journal vouchers yet" />
            </Card>
        </template>

        <Modal
            :open="!!selectedVoucher"
            :title="selectedVoucher ? `${voucherLabel(selectedVoucher)} · ${voucherTypeLabel(selectedVoucher.voucher_type)}` : ''"
            @update:open="onDetailOpenChange"
        >
            <div v-if="selectedVoucher" class="flex flex-col gap-4">
                <div class="grid grid-cols-2 gap-3 text-sm">
                    <div>
                        <p class="text-[10px] font-bold tracking-[.8px] text-text-muted uppercase">Date</p>
                        <p class="text-text-base">{{ formatBsDate(selectedVoucher.date) || '—' }} (BS) · {{ adDate(selectedVoucher.date) }}</p>
                    </div>
                    <div>
                        <p class="text-[10px] font-bold tracking-[.8px] text-text-muted uppercase">Fiscal Year</p>
                        <p class="text-text-base">{{ selectedVoucher.fiscal_year?.name ?? '—' }}</p>
                    </div>
                    <div class="col-span-2">
                        <p class="text-[10px] font-bold tracking-[.8px] text-text-muted uppercase">Narration</p>
                        <p class="text-text-base">{{ selectedVoucher.narration }}</p>
                    </div>
                    <div v-if="selectedVoucher.reason" class="col-span-2">
                        <p class="text-[10px] font-bold tracking-[.8px] text-text-muted uppercase">Reason</p>
                        <p class="text-text-base">{{ selectedVoucher.reason }}</p>
                    </div>
                    <div>
                        <p class="text-[10px] font-bold tracking-[.8px] text-text-muted uppercase">Created By</p>
                        <p class="text-text-base">{{ selectedVoucher.creator?.name ?? '—' }}</p>
                    </div>
                </div>

                <table class="w-full text-sm">
                    <thead>
                        <tr class="border-b border-border-soft text-left text-[11px] font-bold tracking-[.6px] text-text-muted uppercase">
                            <th class="pb-2 font-bold">Account</th>
                            <th class="pb-2 text-right font-bold">Debit</th>
                            <th class="pb-2 text-right font-bold">Credit</th>
                            <th class="pb-2 font-bold">Narration</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr v-for="line in selectedVoucher.lines" :key="line.id" class="border-b border-border-soft last:border-0">
                            <td class="py-2 text-text-base">
                                {{ line.account?.code ? `${line.account.code} — ${line.account.name}` : line.account?.name }}
                            </td>
                            <td class="py-2 text-right [font-variant-numeric:tabular-nums]">{{ formatMoney(line.debit) }}</td>
                            <td class="py-2 text-right [font-variant-numeric:tabular-nums]">{{ formatMoney(line.credit) }}</td>
                            <td class="py-2 text-text-muted">{{ line.narration ?? '—' }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </Modal>

        <Modal :open="!!cancelling" title="Cancel journal voucher" size="compact" @update:open="onCancelOpenChange">
            <form class="flex flex-col gap-4" @submit.prevent="submitCancel">
                <p class="text-sm text-text-muted">
                    This posts a reversing entry for this journal voucher. This cannot be undone.
                </p>
                <div>
                    <label class="mb-1 block text-sm font-semibold text-text-base">Reason <span class="text-danger">*</span></label>
                    <Input v-model="cancelForm.reason" type="text" placeholder="e.g. Entered wrong account" required />
                    <p v-if="cancelForm.errors.reason" class="mt-1 text-sm text-danger">{{ cancelForm.errors.reason }}</p>
                </div>
            </form>

            <template #footer>
                <Button variant="secondary" tone="purple" type="button" @click="cancelling = null">Back</Button>
                <Button variant="primary" tone="purple" type="button" :disabled="cancelForm.processing" @click="submitCancel">
                    Confirm cancellation
                </Button>
            </template>
        </Modal>
    </AppLayout>
</template>
