<?php

use App\Http\Controllers\Tenant\Auth\ImpersonationController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Tenant: Platform-Admin Impersonation
|--------------------------------------------------------------------------
|
| A single-purpose, short-lived (5 minute) signed route that lets a
| platform admin land on this tenant's own domain already logged into the
| `web` guard as that tenant's admin user. The signed URL is only ever
| generated by App\Http\Controllers\Central\Tenants\TenantController::
| impersonate() - never issue or accept one from anywhere else.
|
| Deliberately required OUTSIDE the `auth:web` group in routes/tenant.php:
| the platform admin isn't logged into `web` yet, that's the whole point of
| this route. It still sits inside the outer tenancy-initializing group
| (web / AbortIfTenantSuspended / InitializeTenancyByDomain), so the `User`
| route-model binding below resolves against the correct tenant database.
|
*/

Route::get('/impersonate/{user}', [ImpersonationController::class, 'login'])
    ->middleware('signed')
    ->name('tenant.impersonate');
