<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Permission catalog
|--------------------------------------------------------------------------
|
| Single source of truth for tenant authorization, read through
| App\Support\Permissions\PermissionCatalog. Keys are permanent API: they are
| stored in roles.permissions JSON, so rename one only with a data migration.
| The route to key mapping these were derived from is todo/permissions/ROUTE-MAP.md.
|
| modules      Central entitlement units. `always_on` modules are granted to every
|              tenant; `requires` lists modules that are switched on with it.
| permissions  <resource>.<action> keys in role editor order. `owner_only` keys
|              pass only for the tenant owner and can never be granted to a role.
| default_modules  Modules a tenant gets when created without an explicit list
|              (tests, tinker). The central create form always sends a list.
|
*/

return [
    'modules' => [
        'core' => ['label' => 'Core', 'always_on' => true, 'requires' => []],
        'sales' => ['label' => 'Sales', 'requires' => []],
        'pos' => ['label' => 'Point of sale', 'requires' => ['sales']],
        'agents' => ['label' => 'Sales agents', 'requires' => ['sales']],
        'quotations' => ['label' => 'Quotations', 'requires' => ['sales']],
        'purchases' => ['label' => 'Purchases', 'requires' => []],
        'inventory' => ['label' => 'Inventory', 'requires' => []],
        'accounting' => ['label' => 'Accounting', 'requires' => []],
        'reports' => ['label' => 'Reports', 'requires' => []],
        'admin' => ['label' => 'Administration', 'requires' => []],
    ],

    'permissions' => [
        'accounts.view' => ['module' => 'core', 'group' => 'Chart of accounts', 'label' => 'View chart of accounts'],
        'accounts.create' => ['module' => 'core', 'group' => 'Chart of accounts', 'label' => 'Add account groups, subgroups and accounts'],
        'accounts.edit' => ['module' => 'core', 'group' => 'Chart of accounts', 'label' => 'Edit account groups, subgroups and accounts'],
        'accounts.delete' => ['module' => 'core', 'group' => 'Chart of accounts', 'label' => 'Delete account groups, subgroups and accounts'],
        'opening_balances.import' => ['module' => 'core', 'group' => 'Chart of accounts', 'label' => 'Import opening balances'],
        'opening_balances.cancel' => ['module' => 'core', 'group' => 'Chart of accounts', 'label' => 'Reverse an opening balance import'],
        'customers.view' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'View customers'],
        'customers.create' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Add customers'],
        'customers.edit' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Edit customers'],
        'customers.delete' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Delete customers'],
        'customers.import' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Import customers'],
        'suppliers.view' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'View suppliers'],
        'suppliers.create' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Add suppliers'],
        'suppliers.edit' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Edit suppliers'],
        'suppliers.delete' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Delete suppliers'],
        'suppliers.import' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Import suppliers'],
        'party_ledger.view' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'View customer and supplier ledgers'],
        'party_ledger.print' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Print customer and supplier ledgers'],
        'party_ledger.export' => ['module' => 'core', 'group' => 'Customers and suppliers', 'label' => 'Export customer and supplier ledgers'],
        'items.view' => ['module' => 'core', 'group' => 'Items', 'label' => 'View items'],
        'items.create' => ['module' => 'core', 'group' => 'Items', 'label' => 'Add items'],
        'items.edit' => ['module' => 'core', 'group' => 'Items', 'label' => 'Edit items, units and VAT status'],
        'items.delete' => ['module' => 'core', 'group' => 'Items', 'label' => 'Delete items'],
        'items.import' => ['module' => 'core', 'group' => 'Items', 'label' => 'Import items'],
        'items.print' => ['module' => 'core', 'group' => 'Items', 'label' => 'Print barcode labels'],
        'brands.view' => ['module' => 'core', 'group' => 'Items', 'label' => 'View brands'],
        'brands.manage' => ['module' => 'core', 'group' => 'Items', 'label' => 'Add, edit and delete brands'],
        'item_categories.view' => ['module' => 'core', 'group' => 'Items', 'label' => 'View item categories'],
        'item_categories.manage' => ['module' => 'core', 'group' => 'Items', 'label' => 'Add, edit and delete item categories'],
        'fiscal_year.view' => ['module' => 'core', 'group' => 'Fiscal years', 'label' => 'View fiscal years'],
        'fiscal_year.create' => ['module' => 'core', 'group' => 'Fiscal years', 'label' => 'Add a fiscal year'],
        'fiscal_year.edit' => ['module' => 'core', 'group' => 'Fiscal years', 'label' => 'Post corrections into a reopened fiscal year'],
        'fiscal_year.close_archive' => ['module' => 'core', 'group' => 'Fiscal years', 'label' => 'Close, reopen, relock and archive fiscal years', 'owner_only' => true],
        'fiscal_year_archive.view' => ['module' => 'core', 'group' => 'Fiscal years', 'label' => 'Browse archived fiscal years'],
        'users.manage' => ['module' => 'core', 'group' => 'Users and roles', 'label' => 'Manage users'],
        'roles.manage' => ['module' => 'core', 'group' => 'Users and roles', 'label' => 'Manage roles and permissions', 'owner_only' => true],
        'ownership.transfer' => ['module' => 'core', 'group' => 'Users and roles', 'label' => 'Transfer ownership', 'owner_only' => true],
        'sales.view' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'View sales'],
        'sales.create' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Create sales'],
        'sales.print' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Print sales invoices'],
        'sales.export' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Export sales'],
        'sales.cancel' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Cancel sales'],
        'capital_sales.view' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'View capital sales'],
        'capital_sales.create' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Create capital sales'],
        'capital_sales.print' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Print capital sales'],
        'capital_sales.cancel' => ['module' => 'sales', 'group' => 'Sales', 'label' => 'Cancel capital sales'],
        'sales_returns.view' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'View sales returns'],
        'sales_returns.create' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'Post sales returns against a bill'],
        'sales_return_requests.create' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'Request a sales return'],
        'sales_return_requests.manage' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'Approve or reject return requests'],
        'unlinked_sales_returns.create' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'Post sales returns without a bill'],
        'sales_returns.print' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'Print sales returns'],
        'sales_returns.cancel' => ['module' => 'sales', 'group' => 'Sales returns', 'label' => 'Cancel sales returns'],
        'receipts.view' => ['module' => 'sales', 'group' => 'Receipts', 'label' => 'View receipts'],
        'receipts.create' => ['module' => 'sales', 'group' => 'Receipts', 'label' => 'Record receipts'],
        'receipts.print' => ['module' => 'sales', 'group' => 'Receipts', 'label' => 'Print receipts'],
        'receipts.cancel' => ['module' => 'sales', 'group' => 'Receipts', 'label' => 'Cancel receipts'],
        'pos.view' => ['module' => 'pos', 'group' => 'Point of sale', 'label' => 'Open point of sale'],
        'agents.view' => ['module' => 'agents', 'group' => 'Sales agents', 'label' => 'View agents'],
        'agents.create' => ['module' => 'agents', 'group' => 'Sales agents', 'label' => 'Add agents'],
        'agents.edit' => ['module' => 'agents', 'group' => 'Sales agents', 'label' => 'Edit agents'],
        'agents.delete' => ['module' => 'agents', 'group' => 'Sales agents', 'label' => 'Delete agents'],
        'quotations.view' => ['module' => 'quotations', 'group' => 'Quotations', 'label' => 'View quotations'],
        'quotations.create' => ['module' => 'quotations', 'group' => 'Quotations', 'label' => 'Create quotations'],
        'quotations.edit' => ['module' => 'quotations', 'group' => 'Quotations', 'label' => 'Edit quotations and convert them to sales'],
        'quotations.delete' => ['module' => 'quotations', 'group' => 'Quotations', 'label' => 'Delete quotations'],
        'quotations.print' => ['module' => 'quotations', 'group' => 'Quotations', 'label' => 'Print quotations'],
        'quotations.cancel' => ['module' => 'quotations', 'group' => 'Quotations', 'label' => 'Cancel quotations'],
        'purchases.view' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'View purchases'],
        'purchases.create' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Create purchases'],
        'purchases.print' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Print purchases'],
        'purchases.export' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Export purchases'],
        'purchases.cancel' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Cancel purchases'],
        'capital_purchases.view' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'View capital purchases'],
        'capital_purchases.create' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Create capital purchases'],
        'capital_purchases.print' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Print capital purchases'],
        'capital_purchases.export' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Export capital purchases'],
        'capital_purchases.cancel' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Cancel capital purchases'],
        'capital_purchase_settlements.create' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Settle capital purchases'],
        'capital_purchase_settlements.cancel' => ['module' => 'purchases', 'group' => 'Purchases', 'label' => 'Cancel capital purchase settlements'],
        'purchase_returns.view' => ['module' => 'purchases', 'group' => 'Purchase returns', 'label' => 'View purchase returns'],
        'purchase_returns.create' => ['module' => 'purchases', 'group' => 'Purchase returns', 'label' => 'Post purchase returns against a bill'],
        'unlinked_purchase_returns.create' => ['module' => 'purchases', 'group' => 'Purchase returns', 'label' => 'Post purchase returns without a bill'],
        'purchase_returns.print' => ['module' => 'purchases', 'group' => 'Purchase returns', 'label' => 'Print purchase returns'],
        'purchase_returns.export' => ['module' => 'purchases', 'group' => 'Purchase returns', 'label' => 'Export purchase returns'],
        'purchase_returns.cancel' => ['module' => 'purchases', 'group' => 'Purchase returns', 'label' => 'Cancel purchase returns'],
        'payments.view' => ['module' => 'purchases', 'group' => 'Payments', 'label' => 'View payments'],
        'payments.create' => ['module' => 'purchases', 'group' => 'Payments', 'label' => 'Record payments'],
        'payments.cancel' => ['module' => 'purchases', 'group' => 'Payments', 'label' => 'Cancel payments'],
        'stock_adjustments.view' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'View stock adjustments'],
        'stock_adjustments.create' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Create stock adjustments'],
        'stock_adjustments.print' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Print stock adjustments'],
        'stock_adjustments.cancel' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Cancel stock adjustments'],
        'opening_stock.import' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Import opening stock'],
        'stock_transfers.view' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'View stock transfers'],
        'stock_transfers.create' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Create stock transfers'],
        'stock_transfers.print' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Print stock transfers'],
        'stock_transfers.cancel' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Cancel stock transfers'],
        'stock_conversions.view' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'View production and refining'],
        'stock_conversions.create' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Create production and refining entries'],
        'stock_conversions.print' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Print production and refining entries'],
        'stock_conversions.cancel' => ['module' => 'inventory', 'group' => 'Stock', 'label' => 'Cancel production and refining entries'],
        'stores.view' => ['module' => 'inventory', 'group' => 'Stores and varieties', 'label' => 'View stores'],
        'stores.manage' => ['module' => 'inventory', 'group' => 'Stores and varieties', 'label' => 'Add, edit and delete stores'],
        'item_varieties.view' => ['module' => 'inventory', 'group' => 'Stores and varieties', 'label' => 'View item varieties'],
        'item_varieties.manage' => ['module' => 'inventory', 'group' => 'Stores and varieties', 'label' => 'Add, edit and delete item varieties'],
        'journal_vouchers.view' => ['module' => 'accounting', 'group' => 'Vouchers', 'label' => 'View vouchers'],
        'journal_vouchers.create' => ['module' => 'accounting', 'group' => 'Vouchers', 'label' => 'Post journal vouchers'],
        'cash_bank_vouchers.create' => ['module' => 'accounting', 'group' => 'Vouchers', 'label' => 'Post cash and bank vouchers'],
        'journal_vouchers.print' => ['module' => 'accounting', 'group' => 'Vouchers', 'label' => 'Print vouchers'],
        'journal_vouchers.export' => ['module' => 'accounting', 'group' => 'Vouchers', 'label' => 'Export vouchers'],
        'journal_vouchers.cancel' => ['module' => 'accounting', 'group' => 'Vouchers', 'label' => 'Cancel vouchers'],
        'account_ledger.view' => ['module' => 'accounting', 'group' => 'Account ledger', 'label' => 'View any account ledger'],
        'account_ledger.print' => ['module' => 'accounting', 'group' => 'Account ledger', 'label' => 'Print any account ledger'],
        'account_ledger.export' => ['module' => 'accounting', 'group' => 'Account ledger', 'label' => 'Export any account ledger'],
        'fixed_assets.view' => ['module' => 'accounting', 'group' => 'Fixed assets', 'label' => 'View fixed assets'],
        'fixed_assets.create' => ['module' => 'accounting', 'group' => 'Fixed assets', 'label' => 'Add fixed assets'],
        'fixed_assets.manage' => ['module' => 'accounting', 'group' => 'Fixed assets', 'label' => 'Dispose assets and post depreciation'],
        'financial_statements.view' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'View trial balance, income statement and balance sheet'],
        'financial_statements.print' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Print financial statements'],
        'financial_statements.export' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Export financial statements'],
        'day_book.view' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'View day book'],
        'day_book.print' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Print day book'],
        'day_book.export' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Export day book'],
        'cash_bank_book.view' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'View cash book and bank book'],
        'cash_bank_book.print' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Print cash book and bank book'],
        'cash_bank_book.export' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Export cash book and bank book'],
        'cancelled_documents.view' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'View cancelled documents'],
        'cancelled_documents.export' => ['module' => 'reports', 'group' => 'Accounting reports', 'label' => 'Export cancelled documents'],
        'sales_reports.view' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'View sales reports'],
        'sales_reports.export' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'Export sales reports'],
        'purchase_reports.view' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'View purchase reports'],
        'purchase_reports.export' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'Export purchase reports'],
        'receivables_reports.view' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'View receivables and debtors'],
        'receivables_reports.export' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'Export debtors'],
        'payables_reports.view' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'View payables and creditors'],
        'payables_reports.export' => ['module' => 'reports', 'group' => 'Sales and purchase reports', 'label' => 'Export creditors'],
        'tax_reports.view' => ['module' => 'reports', 'group' => 'Tax reports', 'label' => 'View VAT books, VAT summary and TDS'],
        'tax_reports.export' => ['module' => 'reports', 'group' => 'Tax reports', 'label' => 'Export VAT books and VAT summary'],
        'stock_reports.view' => ['module' => 'reports', 'group' => 'Stock reports', 'label' => 'View stock reports and item ledgers'],
        'stock_reports.print' => ['module' => 'reports', 'group' => 'Stock reports', 'label' => 'Print item ledgers'],
        'stock_reports.export' => ['module' => 'reports', 'group' => 'Stock reports', 'label' => 'Export item ledgers'],
        'stock_valuation.view' => ['module' => 'reports', 'group' => 'Stock reports', 'label' => 'View stock valuation'],
        'activity_log.view' => ['module' => 'admin', 'group' => 'Audit', 'label' => 'View activity log'],
        'print_log.view' => ['module' => 'admin', 'group' => 'Audit', 'label' => 'View print log'],
        'backups.manage' => ['module' => 'admin', 'group' => 'Backups', 'label' => 'Manage backups', 'owner_only' => true],
        'notices.manage' => ['module' => 'admin', 'group' => 'Notices', 'label' => 'Manage dashboard notices'],
    ],

    'default_modules' => [
        'sales', 'pos', 'agents', 'quotations', 'purchases',
        'inventory', 'accounting', 'reports', 'admin',
    ],
];
